### ISSUE TITLE
HEX X, ONESHOT125, Matek F722-STD, SDCard unavailable

### ISSUE THREAD

**Issue by Frontier314** [iNavFlight/inav#3945]
## Current Behavior
Enabling ONESHOT125 or ONESHOT42 ESC protocol on INAV 2.0 running on MatekSYS F722-STD using a HEX X mixer profile, results in SD Card being unavailable (gets stuck with message "Filesystem Starting..."). Tried 6 different SD cards: Class 10, Class 10 U1, Class 10 U3 with 4GB, 16GB, 32GB size, Kingston and Sandisk brands.
The issue is reproduced on all these cards and they all work with the same F722-STD running Betaflight 3.5.2.

## Steps to Reproduce
1. Perform defaults on F722-STD running INAV 2.0, restore the provided diff and save.
2. On the Blackbox tab, the message "Filesystem Starting..." is shown and the card does not start at all.
2. Change ESC protocol to anything else except ONESHOT125 or ONESHOT42, save and reboot.
3. On the Blackbox tab, the card is shown to be ready to accept Blackbox records.

## Expected behavior
The SD Card Blackbox system should work with ONESHOT125 or ONESHOT42 ESC protocol with HEX X mixer profile.

## Additional context
CLI dump diff for INAV 2.0 F722-STD
[F722-STD_INAV200_ONESHOT125.txt](https://github.com/iNavFlight/inav/files/2506061/F722-STD_INAV200_ONESHOT125.txt)

---

- FC Board name and vendor: INAV/MATEKF722
- INAV version string: 2.0.0 Aug 20 2018 / 19:21:31 (dbdd1656a)

**Comment by teckel12** [comment]
@Frontier314 Not to undermine your issue, as it seems this needs to be looked into.  But, have you tried multishot instead?  It would be helpful to know if a different protocol works or not, and I would argue that multishot is a superior protocol anyway.

**Comment by Frontier314** [comment]
@teckel12: Yes, I have tried Multishot/Standard/Brushed with the same setup (without my ESCs connected) and the SD card is recognized. The problem however is not the OneShot125/OneShot42 protocol but the combination of that with Hex X6 mixer; if I keep the same configuration as posted above but change the mixer to Quad X, the SD card(s) are recognized.

My ESCs are Flycolor Raptor 30A running BLHeli 14.6 (or 14.9, I do not remember exactly which of the two) and I am pretty sure they do not support Multishot protocol. Unfortunately, I cannot easily change the ESCs and - frankly - I do not want to as most of the new ESCs of that size run BLHeli32 and only support DSHOT which I think INAV does not currently support. The same set-up works with Betaflight 3.5.2 but I do not want to use Betaflight; I want INAV for the GPS functionality :)

Thank you very much for your time and advice.

**Comment by digitalentity** [comment]
This is odd. Can you post output of `bootlog` and `resources` commands with QUAD and HEX mixer.

**Comment by digitalentity** [comment]
Also, can you try latest development build? Unfortunately I don't have an F722 board at hand to test myself.

[inav_2.1.0_MATEKF722.hex.zip](https://github.com/iNavFlight/inav/files/2507404/inav_2.1.0_MATEKF722.hex.zip)

**Comment by teckel12** [comment]
@Frontier314 Totally fine, just was trying to isolate the issue and suggest a possible work-around.

**Comment by Frontier314** [comment]
> 
> 
> This is odd. Can you post output of `bootlog` and `resources` commands with QUAD and HEX mixer.

@digitalentity: Certainly.

**Hex X mixer:**
```
# bootlog
Time Evt            Description  Parameters
   3:  0          CONFIG_LOADED 
   3:  1       SYSTEM_INIT_DONE 
 259: 19   TIMER_CHANNEL_MAPPED  (1, 1, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (2, 2, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (3, 3, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (4, 4, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (5, 5, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (6, 6, 0, 2)
 259:  2          PWM_INIT_DONE 
 909:  9         GYRO_DETECTION  (7, 0, 0, 0)
1400: 10          ACC_DETECTION  (8, 0, 0, 0)
1501: 11         BARO_DETECTION  (4, 0, 0, 0)
1501: 20        PITOT_DETECTION  (0, 0, 0, 0)
1501: 12          MAG_DETECTION  (0, 0, 0, 0)
1501: 13  RANGEFINDER_DETECTION  (0, 0, 0, 0)
1501:  4       SENSOR_INIT_DONE 
2007:  5          GPS_INIT_DONE 
2007:  7    TELEMETRY_INIT_DONE 
3008:  8           SYSTEM_READY 

# resource
IO:
----------------------
A00: FREE 
A01: FREE 
A02: FREE 
A03: SERIAL2 UART RX
A04: FREE 
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: MOTOR6 OUT
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A13: FREE 
A14: LED2 OUT
A15: FREE 
B00: FREE 
B01: MOTOR5 OUT
B02: FREE 
B03: SPI3 SCK
B04: SPI3 MISO
B05: SPI3 MOSI
B06: I2C1 SCL
B07: I2C1 SDA
B08: FREE 
B09: LED1 OUT
B10: OSD CS
B11: FREE 
B12: FREE 
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: ADC CH1
C01: SDCARD CS
C02: MPU CS
C03: MPU EXTI
C04: ADC CH2
C05: FREE 
C06: MOTOR1 OUT
C07: MOTOR2 OUT
C08: MOTOR3 OUT
C09: MOTOR4 OUT
C10: SERIAL3 UART TX/RX
C11: FREE 
C12: SERIAL5 UART TX/RX
C13: BEEPER OUT
C14: FREE 
C15: FREE 
D02: FREE
```

**Quad X mixer:**
```
# bootlog
Time Evt            Description  Parameters
   3:  0          CONFIG_LOADED 
   3:  1       SYSTEM_INIT_DONE 
 259: 19   TIMER_CHANNEL_MAPPED  (1, 1, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (2, 2, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (3, 3, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (4, 4, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (5, 5, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (6, 6, 0, 2)
 259:  2          PWM_INIT_DONE 
 909:  9         GYRO_DETECTION  (7, 0, 0, 0)
1400: 10          ACC_DETECTION  (8, 0, 0, 0)
1501: 11         BARO_DETECTION  (4, 0, 0, 0)
1501: 20        PITOT_DETECTION  (0, 0, 0, 0)
1501: 12          MAG_DETECTION  (0, 0, 0, 0)
1501: 13  RANGEFINDER_DETECTION  (0, 0, 0, 0)
1501:  4       SENSOR_INIT_DONE 
2007:  5          GPS_INIT_DONE 
2007:  7    TELEMETRY_INIT_DONE 
3008:  8           SYSTEM_READY 

# resource
IO:
----------------------
A00: FREE 
A01: FREE 
A02: FREE 
A03: SERIAL2 UART RX
A04: FREE 
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: MOTOR6 OUT
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A13: FREE 
A14: LED2 OUT
A15: FREE 
B00: FREE 
B01: MOTOR5 OUT
B02: FREE 
B03: SPI3 SCK
B04: SPI3 MISO
B05: SPI3 MOSI
B06: I2C1 SCL
B07: I2C1 SDA
B08: FREE 
B09: LED1 OUT
B10: OSD CS
B11: FREE 
B12: FREE 
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: ADC CH1
C01: SDCARD CS
C02: MPU CS
C03: MPU EXTI
C04: ADC CH2
C05: FREE 
C06: MOTOR1 OUT
C07: MOTOR2 OUT
C08: MOTOR3 OUT
C09: MOTOR4 OUT
C10: SERIAL3 UART TX/RX
C11: FREE 
C12: SERIAL5 UART TX/RX
C13: BEEPER OUT
C14: FREE 
C15: FREE 
D02: FREE
```

**Comment by digitalentity** [comment]
This is even more odd. I see no reason for SDCARD not to work with HEX mixer. Did you have a chance to test SDCard with 2.1-dev firmware?

**Comment by Frontier314** [comment]
> 
> 
> Also, can you try latest development build? Unfortunately I don't have an F722 board at hand to test myself.
> 
> [inav_2.1.0_MATEKF722.hex.zip](https://github.com/iNavFlight/inav/files/2507404/inav_2.1.0_MATEKF722.hex.zip)

@digitalentity: On the developer build you've provided, the SD card is correctly detected and utilized on both Hex X and Quad X mixers.

Below are the output of `bootlog` and `resource` commands respectively running INAV development build.

**Hex X mixer:**
```
# bootlog
Time Evt            Description  Parameters
   3:  0          CONFIG_LOADED 
   3:  1       SYSTEM_INIT_DONE 
 259: 19   TIMER_CHANNEL_MAPPED  (1, 1, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (2, 2, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (3, 3, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (4, 4, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (5, 5, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (6, 6, 0, 2)
 259:  2          PWM_INIT_DONE 
 909:  9         GYRO_DETECTION  (7, 0, 0, 0)
1400: 10          ACC_DETECTION  (8, 0, 0, 0)
1501: 11         BARO_DETECTION  (4, 0, 0, 0)
1501: 20        PITOT_DETECTION  (0, 0, 0, 0)
1501: 12          MAG_DETECTION  (0, 0, 0, 0)
1501: 13  RANGEFINDER_DETECTION  (0, 0, 0, 0)
1501:  4       SENSOR_INIT_DONE 
2006:  5          GPS_INIT_DONE 
2006:  7    TELEMETRY_INIT_DONE 
3007:  8           SYSTEM_READY 

# resource
IO:
----------------------
A00: FREE 
A01: FREE 
A02: FREE 
A03: SERIAL2 UART RX
A04: FREE 
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: MOTOR6 OUT
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A13: FREE 
A14: LED2 OUT
A15: FREE 
B00: FREE 
B01: MOTOR5 OUT
B02: FREE 
B03: SPI3 SCK
B04: SPI3 MISO
B05: SPI3 MOSI
B06: I2C1 SCL
B07: I2C1 SDA
B08: FREE 
B09: LED1 OUT
B10: OSD CS
B11: FREE 
B12: FREE 
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: ADC CH1
C01: SDCARD CS
C02: MPU CS
C03: MPU EXTI
C04: ADC CH2
C05: FREE 
C06: MOTOR1 OUT
C07: MOTOR2 OUT
C08: MOTOR3 OUT
C09: MOTOR4 OUT
C10: SERIAL3 UART TX/RX
C11: FREE 
C12: SERIAL5 UART TX/RX
C13: BEEPER OUT
C14: FREE 
C15: FREE 
D02: FREE
```

**Quad X mixer:**
```
# bootlog
Time Evt            Description  Parameters
   3:  0          CONFIG_LOADED 
   3:  1       SYSTEM_INIT_DONE 
 259: 19   TIMER_CHANNEL_MAPPED  (1, 1, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (2, 2, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (3, 3, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (4, 4, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (5, 5, 0, 2)
 259: 19   TIMER_CHANNEL_MAPPED  (6, 6, 0, 2)
 259:  2          PWM_INIT_DONE 
 909:  9         GYRO_DETECTION  (7, 0, 0, 0)
1400: 10          ACC_DETECTION  (8, 0, 0, 0)
1501: 11         BARO_DETECTION  (4, 0, 0, 0)
1501: 20        PITOT_DETECTION  (0, 0, 0, 0)
1501: 12          MAG_DETECTION  (0, 0, 0, 0)
1501: 13  RANGEFINDER_DETECTION  (0, 0, 0, 0)
1501:  4       SENSOR_INIT_DONE 
2006:  5          GPS_INIT_DONE 
2007:  7    TELEMETRY_INIT_DONE 
3007:  8           SYSTEM_READY 

# resource
IO:
----------------------
A00: FREE 
A01: FREE 
A02: FREE 
A03: SERIAL2 UART RX
A04: FREE 
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: MOTOR6 OUT
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A13: FREE 
A14: LED2 OUT
A15: FREE 
B00: FREE 
B01: MOTOR5 OUT
B02: FREE 
B03: SPI3 SCK
B04: SPI3 MISO
B05: SPI3 MOSI
B06: I2C1 SCL
B07: I2C1 SDA
B08: FREE 
B09: LED1 OUT
B10: OSD CS
B11: FREE 
B12: FREE 
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: ADC CH1
C01: SDCARD CS
C02: MPU CS
C03: MPU EXTI
C04: ADC CH2
C05: FREE 
C06: MOTOR1 OUT
C07: MOTOR2 OUT
C08: MOTOR3 OUT
C09: MOTOR4 OUT
C10: SERIAL3 UART TX/RX
C11: FREE 
C12: SERIAL5 UART TX/RX
C13: BEEPER OUT
C14: FREE 
C15: FREE 
D02: FREE
```
